#!/bin/bash  

echo "--------"
echo "$ cd /Users/macserver/zf/svn/git_assetmanager/mac/GameCR/Assets/../../../version.git/"
cd /Users/macserver/zf/svn/git_assetmanager/mac/GameCR/Assets/../../../version.git/
echo "--------"
echo "$ git branch"
git branch
echo "--------"
echo "$ git tag"
git tag
echo "--------"
echo "$ git tag -a osx_ver0.0.0_nocenter -m \"add tag osx_ver0.0.0_nocenter\""
git tag -a osx_ver0.0.0_nocenter -m "add tag osx_ver0.0.0_nocenter"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_m4399 -m \"add tag osx_ver0.0.0_m4399\""
git tag -a osx_ver0.0.0_m4399 -m "add tag osx_ver0.0.0_m4399"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_xiaomi -m \"add tag osx_ver0.0.0_xiaomi\""
git tag -a osx_ver0.0.0_xiaomi -m "add tag osx_ver0.0.0_xiaomi"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_guopan -m \"add tag osx_ver0.0.0_guopan\""
git tag -a osx_ver0.0.0_guopan -m "add tag osx_ver0.0.0_guopan"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_facebook -m \"add tag osx_ver0.0.0_facebook\""
git tag -a osx_ver0.0.0_facebook -m "add tag osx_ver0.0.0_facebook"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_shouyougu -m \"add tag osx_ver0.0.0_shouyougu\""
git tag -a osx_ver0.0.0_shouyougu -m "add tag osx_ver0.0.0_shouyougu"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_nocenters0 -m \"add tag osx_ver0.0.0_nocenters0\""
git tag -a osx_ver0.0.0_nocenters0 -m "add tag osx_ver0.0.0_nocenters0"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_uc -m \"add tag osx_ver0.0.0_uc\""
git tag -a osx_ver0.0.0_uc -m "add tag osx_ver0.0.0_uc"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_qihu360 -m \"add tag osx_ver0.0.0_qihu360\""
git tag -a osx_ver0.0.0_qihu360 -m "add tag osx_ver0.0.0_qihu360"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_huawei -m \"add tag osx_ver0.0.0_huawei\""
git tag -a osx_ver0.0.0_huawei -m "add tag osx_ver0.0.0_huawei"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_yyb -m \"add tag osx_ver0.0.0_yyb\""
git tag -a osx_ver0.0.0_yyb -m "add tag osx_ver0.0.0_yyb"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_ucube -m \"add tag osx_ver0.0.0_ucube\""
git tag -a osx_ver0.0.0_ucube -m "add tag osx_ver0.0.0_ucube"
echo "--------"
echo "$ git tag -a osx_ver0.0.0_quick -m \"add tag osx_ver0.0.0_quick\""
git tag -a osx_ver0.0.0_quick -m "add tag osx_ver0.0.0_quick"
echo "--------"
echo "$ git tag"
git tag
